In [224]:
hp = [
      "Harry Potter & the Philosopher’s Stone",
      "Harry Potter and the Philosopher’s Stone",
      "Harry Potter & the Sorcerer’s Stone",
      "Harry Potter and the Sorcerer’s Stone",
      "Harry Potter One",
      "Harry Potter 1",
      "First Harry Potter Movie"
]

In [196]:
import pandas as pd
movies_df = pd.read_csv("mismatched_titles_sample.csv")
movies_np = movies_df.to_numpy()
movies = []
for m in movies_np:
    movies.append(m[0])
print(movies)

['Demon Slayer - Kimetsu No Yaiba - The Movie: Mugen Train', 'DEMON SLAYER THE MOVIE: MUGEN TRAIN', 'Tom & Jerry', 'Tom y Jerry', 'Tom & Jerry The Movie', 'Maya the Bee 3: The Golden Orb', 'MAIJA MEHILÄINEN JA KULTAINEN AARRE', 'Peter Rabbit 2: The Runaway', 'Peter Rabbit 2: A la fuga', 'Pelle Kanin 2: På rymmen', 'Peter Rabbit: Coelho à Solta', 'Peter Hase 2 - Ein Hase macht sich vom Acker', 'Minions: El origen de Gru', 'KÄTYRIT: GRUN TARINA', 'Minions: The Rise of Gru', 'BLACK WIDOW', 'Black Widow', 'Viuda Negra', 'Marvel Black Widow', 'FAST & FURIOUS 9', 'Fast and Furious 9', 'Fast & Furious 9', 'F9 - Fast & Furious 9', 'Fast & Furious Presents: Hobbs & Shaw', 'Space Jam 2', 'Space Jam: A New Legacy', 'Doctor Strange: In the Multiverse of Madness', 'Doctor Strange in the Multiverse of Madness', 'The Matrix 4', 'The Matrix Resurrections', 'No Time To Die', 'Sin tiempo para morir', '007 No Time to Die', 'The Boss Baby: Family Business', 'Baby Boss 2 : une affaire de famille', 'Ainbo: 

In [8]:
from bert_embedding import BertEmbedding

bert = BertEmbedding(model='bert_24_1024_16', dataset_name='book_corpus_wiki_en_cased')
results = bert(hp)
print(results)

ModuleNotFoundError: No module named 'bert_embedding'

In [188]:
## CHECK GOOGLE

from __future__ import print_function
import json
import urllib

def call_google(title):
    api_key = "AIzaSyCTwleqUTeOWC0nPMqqUdq8w8DTyUcWbno"
    query = title
    service_url = 'https://kgsearch.googleapis.com/v1/entities:search'
    params = {
        'query': query,
        # 'ids': "Movie",
        'limit': 10,
        'indent': True,
        'key': api_key,
    }
    url = service_url + '?' + urllib.parse.urlencode(params)
    response = json.loads(urllib.request.urlopen(url).read())
    return response['itemListElement']
  
# Filter out entities that are not movies
def filter_movies(results):
    filtered_results = []
    for element in results:
        if "Movie" in element['result']['@type']:
            filtered_results.append(element)

    print("-------MOVIE-------")
    for element in filtered_results:
        print(element['result']['name'] + ' (' + str(element['resultScore']) + ')')
    return filtered_results


def check_google(m1,m2):
    m1_info = call_google(m1)
    m2_info = call_google(m2)
    m1_info = filter_movies(m1_info)
    m2_info = filter_movies(m2_info)
    is_same = m1_info[0]['result']['name'] == m2_info[0]['result']['name']
    print("[CHECK GOOGLE]: " + str(is_same))
    return is_same
        

In [152]:
import requests
api_key ='040c8b0d45e3dc62d9afb2dad6bc2743'
query = "Harry Potter One"
response = requests.get('https://api.themoviedb.org/3/search/movie?api_key=' +api_key+'&query=' + query)
response_tmdb = response.json()
print(response_tmdb)
  

{'page': 1, 'results': [], 'total_pages': 0, 'total_results': 0}


In [214]:
#CHECK NLP 

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer 
import nltk
import numpy as np
from num2words import num2words

def get_tokens(title):
    lemmatizer = WordNetLemmatizer() 
    title = nltk.word_tokenize(title.lower())
    tokens = []
    for word in title:
        #remove stop words and '&'
        if not word in set(stopwords.words('english')) and word != "&":
            if not word.isnumeric():
                tokens.append(lemmatizer.lemmatize(word))
                continue

            word = num2words(int(word))
            tokens.append(lemmatizer.lemmatize(word))
    return tokens


# Check if the titles tokens are the same
def check_tokens(m1, m2):
    m1_token = get_tokens(m1)
    m2_token = get_tokens(m2)
    m1_token.sort()
    m2_token.sort()
    #print("[CHECK TOKENS]: " + str(m1_token == m2_token))
    #print(m1_token, m2_token)
    return m1_token == m2_token



# Check if names are exactly the same
def check_same_name(m1, m2):
    #print("[CHECK SAME NAME]: " + str(m1.lower()==m2.lower()))
    return m1.lower()==m2.lower()

# check_tokens("Harry Potter One", "Harry Potter 1")

In [215]:
def is_same_movie(m1, m2):
    if(check_same_name(m1, m2)):
        return True
    if(check_tokens(m1, m2)):
        return True
    # if(check_google(m1,m2)):
    #     return True
    return False

In [213]:
is_same_movie("Harry Potter One", "First Harry Potter Movie")

False

In [230]:
graph = np.zeros((len(hp), len(hp)))
for row, movie1 in enumerate(hp):
    col = row
    if(col >= len(hp)):
        continue
    for movie2 in hp[col:]:
        graph[row][col]=is_same_movie(movie1, movie2)
        col+=1
        
print(graph)

[[1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
