In [282]:
hp = [
      "Harry Potter & the Philosopher’s Stone",
      "Harry Potter and the Philosopher’s Stone",
      "Harry Potter & the Sorcerer’s Stone",
      "Harry Potter and the Sorcerer’s Stone",
      "Harry Potter One",
      "Harry Potter 1",
      "First Harry Potter Movie",
      "Harry Potter and the Deathly Hallows – Part 1",
      "Harry Potter and the Chamber of Secrets",
      "Harry Potter 2"

]

In [196]:
import pandas as pd
movies_df = pd.read_csv("mismatched_titles_sample.csv")
movies_np = movies_df.to_numpy()
movies = []
for m in movies_np:
    movies.append(m[0])
print(movies)

['Demon Slayer - Kimetsu No Yaiba - The Movie: Mugen Train', 'DEMON SLAYER THE MOVIE: MUGEN TRAIN', 'Tom & Jerry', 'Tom y Jerry', 'Tom & Jerry The Movie', 'Maya the Bee 3: The Golden Orb', 'MAIJA MEHILÄINEN JA KULTAINEN AARRE', 'Peter Rabbit 2: The Runaway', 'Peter Rabbit 2: A la fuga', 'Pelle Kanin 2: På rymmen', 'Peter Rabbit: Coelho à Solta', 'Peter Hase 2 - Ein Hase macht sich vom Acker', 'Minions: El origen de Gru', 'KÄTYRIT: GRUN TARINA', 'Minions: The Rise of Gru', 'BLACK WIDOW', 'Black Widow', 'Viuda Negra', 'Marvel Black Widow', 'FAST & FURIOUS 9', 'Fast and Furious 9', 'Fast & Furious 9', 'F9 - Fast & Furious 9', 'Fast & Furious Presents: Hobbs & Shaw', 'Space Jam 2', 'Space Jam: A New Legacy', 'Doctor Strange: In the Multiverse of Madness', 'Doctor Strange in the Multiverse of Madness', 'The Matrix 4', 'The Matrix Resurrections', 'No Time To Die', 'Sin tiempo para morir', '007 No Time to Die', 'The Boss Baby: Family Business', 'Baby Boss 2 : une affaire de famille', 'Ainbo: 

In [257]:
## CHECK GOOGLE

from __future__ import print_function
import json
import urllib

def call_google(title):
    api_key = "AIzaSyCTwleqUTeOWC0nPMqqUdq8w8DTyUcWbno"
    query = title
    service_url = 'https://kgsearch.googleapis.com/v1/entities:search'
    params = {
        'query': query,
        # 'ids': "Movie",
        'limit': 10,
        'indent': True,
        'key': api_key,
    }
    url = service_url + '?' + urllib.parse.urlencode(params)
    response = json.loads(urllib.request.urlopen(url).read())
    return response['itemListElement']

        

In [261]:
# Cache Google's API results
google_results = {}
for movie in hp:
    google_results[movie] = call_google(movie)

for movie in movies:
    google_results[movie] = call_google(movie)

print(google_results)

detailedDescription': {'license': 'https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License', 'url': 'https://en.wikipedia.org/wiki/Godzilla,_King_of_the_Monsters_(comic_book)', 'articleBody': 'Godzilla, King of the Monsters is a comic book title that was published by Marvel Comics.'}, '@id': 'kg:/g/11fw9kl48s', 'name': 'Godzilla, King of the Monsters', '@type': ['Thing']}}, {'@type': 'EntitySearchResult', 'result': {'@id': 'kg:/g/11f26s8m5t', 'name': 'Ending', '@type': ['Thing'], 'description': 'Song by Akira Ifukube'}, 'resultScore': 95.95491027832031}], 'Godzilla II - King of the Monsters': [{'resultScore': 94701.6015625, 'result': {'description': '2019 film', 'name': 'Godzilla: King of the Monsters', '@type': ['Movie', 'Thing', 'CreativeWork'], '@id': 'kg:/g/11c6gz2d_5', 'detailedDescription': {'articleBody': "Godzilla: King of the Monsters is a 2019 American monster film directed and co-written by Michael Dougherty. A sequel to G

In [303]:
# CHECK GOOGLE

# Filter out entities that are not movies
def filter_movies(results):
    filtered_results = []
    for element in results:
        if "Movie" in element['result']['@type']:
            filtered_results.append(element)

    # print("-------MOVIE-------")
    # for element in filtered_results:
    #     print(element['result']['name'] + ' (' + str(element['resultScore']) + ')')
    return filtered_results


def check_google(m1,m2):
    m1_info = google_results[m1]
    m2_info = google_results[m2]
    m1_info = filter_movies(m1_info)
    m2_info = filter_movies(m2_info)

    #TODO: if there are no movie results, call the api again asking for more data
    if(len(m1_info)==0 or len(m2_info)==0):
        return False
    is_same = m1_info[0]['result']['name'] == m2_info[0]['result']['name']
    # print("[CHECK GOOGLE]: " + str(is_same))
    return is_same

In [214]:
#CHECK NLP 

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer 
import nltk
import numpy as np
from num2words import num2words

def get_tokens(title):
    lemmatizer = WordNetLemmatizer() 
    title = nltk.word_tokenize(title.lower())
    tokens = []
    for word in title:
        #remove stop words and '&'
        if not word in set(stopwords.words('english')) and word != "&":
            if not word.isnumeric():
                tokens.append(lemmatizer.lemmatize(word))
                continue

            word = num2words(int(word))
            tokens.append(lemmatizer.lemmatize(word))
    return tokens


# Check if the titles tokens are the same
def check_tokens(m1, m2):
    m1_token = get_tokens(m1)
    m2_token = get_tokens(m2)
    m1_token.sort()
    m2_token.sort()
    #print("[CHECK TOKENS]: " + str(m1_token == m2_token))
    #print(m1_token, m2_token)
    return m1_token == m2_token



# Check if names are exactly the same
def check_same_name(m1, m2):
    #print("[CHECK SAME NAME]: " + str(m1.lower()==m2.lower()))
    return m1.lower()==m2.lower()

# check_tokens("Harry Potter One", "Harry Potter 1")

In [264]:
def is_same_movie(m1, m2):
    if(check_same_name(m1, m2)):
        return True
    if(check_tokens(m1, m2)):
        return True
    if(check_google(m1,m2)):
         return True
    return False

In [304]:
#DRAW GRAPH
import matplotlib.pyplot as plt
import networkx as nx
from scipy.sparse.csgraph import connected_components

def get_graph(movies):
    graph = np.zeros((len(movies), len(movies)))
    for row, movie1 in enumerate(movies):
        col = row+1
        if(col >= len(movies)):
            continue
        for movie2 in movies[col:]:
            graph[row][col]=is_same_movie(movie1, movie2)
            col+=1
            
    print(graph)
    return graph

def show_graph_with_labels(adjacency_matrix, mylabels):
    rows, cols = np.where(adjacency_matrix == 1)
    edges = zip(rows.tolist(), cols.tolist())
    gr = nx.Graph()
    gr.add_edges_from(edges)
    nx.draw(gr, node_size=500, labels = mylabels, with_labels=True)
    plt.show()

def plot_graph(graph, labels):
    labeldict = {}
    for i, name in enumerate(labels):
        labeldict[i] = name
    print(labeldict)
    show_graph_with_labels(graph, labeldict)


def get_clusters(graph, labels):
    clusters = connected_components(graph)
    clusters_dic = {}
    for i, cluster_no in enumerate(clusters[1]):
        movies_so_far = clusters_dic.get(cluster_no, [])
        movies_so_far.append(labels[i])
        clusters_dic[cluster_no] = movies_so_far
    print(clusters_dic)

get_clusters(get_graph(movies), movies)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]
{0: ['Demon Slayer - Kimetsu No Yaiba - The Movie: Mugen Train', 'DEMON SLAYER THE MOVIE: MUGEN TRAIN'], 1: ['Tom & Jerry', 'Tom y Jerry', 'Tom & Jerry The Movie'], 2: ['Maya the Bee 3: The Golden Orb'], 3: ['MAIJA MEHILÄINEN JA KULTAINEN AARRE'], 4: ['Peter Rabbit 2: The Runaway', 'Peter Rabbit 2: A la fuga', 'Pelle Kanin 2: På rymmen', 'Peter Rabbit: Coelho à Solta', 'Peter Hase 2 - Ein Hase macht sich vom Acker'], 5: ['Minions: El origen de Gru', 'KÄTYRIT: GRUN TARINA', 'Minions: The Rise of Gru'], 6: ['BLACK WIDOW', 'Black Widow', 'Viuda Negra', 'Marvel Black Widow'], 7: ['FAST & FURIOUS 9', 'Fast and Furious 9', 'Fast & Furious 9', 'F9 - Fast & Furious 9'], 8: ['Fast & Furious Presents: Hobbs & Shaw'], 9: ['Space Jam 2', 'Space Jam: A New Legacy'], 10: ['Doctor Strange: In the Multiverse of Madness', 'Doctor Strange in the Mult

In [237]:
is_same_movie("Harry Potter & the Philosopher’s Stone", "Harry Potter und der Stein der Weisen (2001)")
is_same_movie("Harry Potter and the Deathly Hallows – Part 1", "Harry Potter und der Stein der Weisen (2001)")
is_same_movie("Harry Potter & the Philosopher’s Stone", "Harry Potter and the Deathly Hallows – Part 1")


-------MOVIE-------
Harry Potter and the Philosopher's Stone (113216.796875)
Harry Potter and the Chamber of Secrets (201.3001251220703)
-------MOVIE-------
Harry Potter and the Philosopher's Stone (63.07793045043945)
[CHECK GOOGLE]: True
-------MOVIE-------
Harry Potter and the Deathly Hallows – Part 1 (129699.15625)
Harry Potter and the Deathly Hallows – Part 2 (569.8067626953125)
Harry Potter and the Goblet of Fire (156.4422302246094)
Harry Potter and the Half-Blood Prince (143.0310668945312)
-------MOVIE-------
Harry Potter and the Philosopher's Stone (63.07793045043945)
[CHECK GOOGLE]: False
-------MOVIE-------
Harry Potter and the Philosopher's Stone (113216.796875)
Harry Potter and the Chamber of Secrets (201.3001251220703)
-------MOVIE-------
Harry Potter and the Deathly Hallows – Part 1 (129699.15625)
Harry Potter and the Deathly Hallows – Part 2 (569.8067626953125)
Harry Potter and the Goblet of Fire (156.4422302246094)
Harry Potter and the Half-Blood Prince (143.031066894531

False